language: python
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database postgres;' -U postgres
install:
  - pip install -r requirements.txt
script:
  - py.test --cov-config .coveragerc --cov=app   tests/
  - coverage report
after_success:
  - coveralls
  - pytest
